name = "MurrellGroupRegistry"
uuid = "07ab66e7-1dc6-449c-9cb1-c43c93e1f98e"
repo = "https://github.com/MurrellGroup/MurrellGroupRegistry"

[packages]
021020d5-7125-488f-a684-9e3366e41e56 = { name = "ONIONop", path = "O/ONIONop" }
0bca4874-a2b8-4dca-bc03-d2d86e344f1f = { name = "PyBoltz", path = "P/PyBoltz" }
30ecd5e8-21b5-49d6-a4db-4371c2e4ee05 = { name = "SeqUMAP", path = "S/SeqUMAP" }
31c70f10-a750-4521-b13c-797315ae2933 = { name = "Microfloats", path = "M/Microfloats" }
434c8270-3839-45f3-8f5c-492a580b2514 = { name = "ColabMPNN", path = "C/ColabMPNN" }
46554747-bf56-4f19-bae7-0bd76bb7d340 = { name = "GGUF", path = "G/GGUF" }
4aa014a1-818e-4fc4-8cd2-74bff3621e60 = { name = "Flatom", path = "F/Flatom" }
5b4e93c8-7b6e-4682-b400-fc3b238f52b1 = { name = "Flowfusion", path = "F/Flowfusion" }
6e960f36-814a-4ceb-8c87-6ab5da0e9bff = { name = "TMscore", path = "T/TMscore" }
77b3afcc-388a-4e14-926d-b99c82d1a01f = { name = "ProtPlot", path = "P/ProtPlot" }
814a5788-1061-474f-a71f-873f087d5d12 = { name = "InvariantPointAttention", path = "I/InvariantPointAttention" }
a25fa8c1-e8fe-40fb-8be2-d139e369b1d5 = { name = "MatrixSign", path = "M/MatrixSign" }
ae93bb3c-0630-4e85-811e-b7d91ad6ecbd = { name = "MessagePassingIPA", path = "M/MessagePassingIPA" }
b58c8408-13c4-4787-8733-7038ae624acf = { name = "BitPacking", path = "B/BitPacking" }
ba507b30-8e11-4219-9ced-db99387ea03d = { name = "PyProteinMPNN", path = "P/PyProteinMPNN" }
bf3ea083-9801-4107-aa43-922d748a66a0 = { name = "ProteinRefolding", path = "P/ProteinRefolding" }
c88d15bf-97e9-4e47-a023-49db67277a02 = { name = "ProteinBenchmarkTools", path = "P/ProteinBenchmarkTools" }
cfe89787-7cb0-4640-afff-52e887d57b7a = { name = "TaxMax", path = "T/TaxMax" }
da1daca8-4fb4-4ba0-bee1-16070df54f00 = { name = "Microscaling", path = "M/Microscaling" }
df93d313-1126-4eb6-ac29-b325d5898587 = { name = "DLProteinFormats", path = "D/DLProteinFormats" }
e879419d-bb0f-4252-adee-d266c51ac92d = { name = "ForwardBackward", path = "F/ForwardBackward" }
ee879965-e6d3-49bd-8e05-89e960000d8e = { name = "ProteinAnnotation", path = "P/ProteinAnnotation" }
eeb6ee5c-f953-4f60-8482-00c4fb7bc198 = { name = "NNop", path = "N/NNop" }
f304b33a-538b-441c-bfb5-9e50a8d4c9a8 = { name = "BranchingFlows", path = "B/BranchingFlows" }
fdebf6c2-71da-43a1-b539-c3bc3e09c5c6 = { name = "Onion", path = "O/Onion" }
